### ISSUE TITLE
Two controllers on connect

### ISSUE THREAD

**Issue by phush0** [epigramx/ds4drv-cemuhook#4]
I am using your application and Dualshock 4, problem is that after connecting controller with USB or Bluetooth, in Cemu I see two controllers, first one is with working keys and motion control, second one is with working rumble. So none of controllers have full functions. Ubuntu 18.04. I can attach some logs or ... what ever is needed.

**Comment by epigramx** [comment]
Not sure if you have another issue, but use the "Also use for buttons/axes" option in the Cemuhook option in Cemu's Options and then only turn up the slider of Rumble for the XInput-type controller in Cemu's input options (make sure it emulates a Wii U GamePad), because ds4drv takes over wine's XInput emulation's buttons.

**Comment by phush0** [comment]
Thank you for help. It is working like this. I see two controllers:
controller 1 - working buttons and motion - rumble slider is gray;
controller 2 - working rumble - but buttons are not working in settings;
So.
select 1, configure buttons, select 2 - configure rubmle and leave it that way. Now everything is working. You have to use "Also use for buttons/axes"
